### ISSUE TITLE
Rails configuration integration

### ISSUE THREAD

**Issue by seanpdoyle** [thoughtbot/action_client#9]
Clients might want to declare a root `default url:` value like so:

```ruby
class ArticlesClient < ActionClient::Base
  default url: "https://example.com"
end
```

However, that URL might vary across environments.

[`Rails.application.config_for`][config_for] is an environment-aware tool for reading configuration files. 

Establishing conventions for how to integrate with `config_for` could be helpful.

For example, consider a `config/clients/articles.yml` file that declares a URL for each environment:

```yaml
# config/clients/articles.yml
default: &default
  url: "https://staging.example.com"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: "https://example.com"
```

Consider a potential `.configuration` method provided by `ActionClient::Base` that is pre-wired to read from that file:

```ruby
class ArticlesClient < ActionClient::Base
  default url: configuration.url
end
```

For sensitive values, consider embedding encrypted credentials directly into the `.yml` file through ERB:

```yaml
# config/clients/articles.yml
default: &default
  url: "https://staging.example.com"
  client_secret: "junk"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: "https://example.com"
  client_secret: <%= Rails.application.credentials[:articles].client_secret %>
```

Then, call that value from the client:

```ruby
class ArticlesClient < ActionClient::Base
  default url: configuration.url
  default headers: {
    "X-Api-Key": configuration.client_secret,
   }
end
```

[config_for]: https://api.rubyonrails.org/classes/Rails/Application.html#method-i-config_for
